import { Category, LiveStall, Workshop } from './types';

export const HAMPER_GALLERY_IMAGES: string[] = [
  '/hampers/hamper1.webp',
  '/hampers/hamper2.webp',
  '/hampers/hamper3.webp',
  '/hampers/hamper4.webp',
  '/hampers/hamper5.webp',
  '/hampers/hamper6.webp',
  '/hampers/hamper7.webp',
  '/hampers/hamper8.webp',
  '/hampers/hamper9.webp',
  '/hampers/hamper10.webp',
  '/hampers/hamper11.webp',
  '/hampers/hamper12.webp',
  '/hampers/hamper13.webp',
  '/hampers/hamper14.webp',
  '/hampers/hamper15.webp',
  '/hampers/hamper16.webp',
  '/hampers/hamper17.webp',
  '/hampers/hamper18.webp',
];

export const CORPORATE_ADULT_GALLERY_IMAGES: string[] = [
  '/Corporate-adults/corporate1.webp',
  '/Corporate-adults/corporate2.webp',
  '/Corporate-adults/corporate3.webp',
  '/Corporate-adults/corporate4.webp',
  '/Corporate-adults/corporate5.webp',
  '/Corporate-adults/corporate6.webp',
  '/Corporate-adults/corporate7.webp',
  '/Corporate-adults/corporate8.webp',
  '/Corporate-adults/corporate9.webp',
  '/Corporate-adults/corporate10.webp',
  '/Corporate-adults/corporate11.webp',
  '/Corporate-adults/corporate12.webp',
  '/Corporate-adults/corporate13.webp',
  '/Corporate-adults/corporate14.webp',
  '/Corporate-adults/corporate15.webp',
  '/Corporate-adults/corporate16.webp',
  '/Corporate-adults/corporate17.webp',
  '/Corporate-adults/corporate18.webp',
  '/Corporate-adults/corporate19.webp',
  '/Corporate-adults/corporate20.webp',
  '/Corporate-adults/corporate21.webp',
  '/Corporate-adults/corporate22.webp',
  '/Corporate-adults/corporate23.webp',
  '/Corporate-adults/corporate24.webp',
  '/Corporate-adults/corporate25.webp',
  '/Corporate-adults/corporate26.webp',
  '/Corporate-adults/corporate27.webp',
  '/Corporate-adults/corporate28.webp',
  '/Corporate-adults/corporate29.webp',
  '/Corporate-adults/corporate30.webp',
  '/Corporate-adults/corporate31.webp',
  '/Corporate-adults/corporate32.webp',
];

export const RETURN_GIFT_GALLERY_IMAGES: string[] = [
  '/return-gift/return1.webp',
  '/return-gift/return2.webp',
  '/return-gift/return3.webp',
  '/return-gift/return4.webp',
  '/return-gift/return5.webp',
  '/return-gift/return6.webp',
  '/return-gift/return7.webp',
  '/return-gift/return8.webp',
  '/return-gift/return9.webp',
  '/return-gift/return10.webp',
  '/return-gift/return11.webp',
  '/return-gift/return13.webp',
  '/return-gift/return14.webp',
  '/return-gift/return15.webp',
  '/return-gift/return16.webp',
  '/return-gift/return17.webp',
  '/return-gift/return18.webp',
  '/return-gift/return19.webp',
  '/return-gift/return20.webp',
  '/return-gift/return21.webp',
  '/return-gift/return22.webp',
  '/return-gift/return23.webp',
  '/return-gift/return24.webp',
  '/return-gift/return25.webp',
  '/return-gift/return26.webp',
  '/return-gift/return27.webp',
  '/return-gift/return28.webp',
  '/return-gift/return29.webp',
  '/return-gift/return30.webp',
];

export const RESIN_GALLERY_IMAGES: string[] = [
  '/Resin-art/resin1.webp',
  '/Resin-art/resin2.webp',
  '/Resin-art/resin3.webp',
  '/Resin-art/resin4.webp',
  '/Resin-art/resin5.webp',
  '/Resin-art/resin6.webp',
  '/Resin-art/resin7.webp',
  '/Resin-art/resin8.webp',
  '/Resin-art/resin9.webp',
  '/Resin-art/resin10.webp',
  '/Resin-art/resin11.webp',
  '/Resin-art/resin12.webp',
  '/Resin-art/resin13.webp',
  '/Resin-art/resin14.webp',
  '/Resin-art/resin15.webp',
  '/Resin-art/resin16.webp',
  '/Resin-art/resin17.webp',
  '/Resin-art/resin18.webp',
  '/Resin-art/resin19.webp',
  '/Resin-art/resin20.webp',
  '/Resin-art/resin21.webp',
  '/Resin-art/resin22.webp',
  '/Resin-art/resin23.webp',
  '/Resin-art/resin24.webp',
  '/Resin-art/resin25.webp',
  '/Resin-art/resin26.webp',
  '/Resin-art/resin27.webp',
  '/Resin-art/resin28.webp',
  '/Resin-art/resin29.webp',
  '/Resin-art/resin30.webp',
];

export const WORKSHOPS: Workshop[] = [
  {
    id: 'monogram-art',
    title: 'Monogram Art',
    description: 'Bring creativity, colour, and personal expression together with our Monogram Decorating art station. Each participant gets an MDF initial cutout and transforms it into a decorative piece using paints, stones, crystals, pearls, and embellishments. Guests layer textures, colours, and patterns to turn a simple letter into personalised decor. The process is easy, guided, mess-controlled, and enjoyable for kids, teens, and adults. Perfect for birthday parties, school workshops, exhibitions, festive celebrations, and corporate events. Everyone takes home a meaningful monogram keepsake that reflects their style.',
    image: '/Kids-art/monogram.webp',
    categories: [Category.KIDS, Category.CORPORATE_ADULT, Category.RETURN_GIFTS]
  },
  {
    id: 'build-a-bear',
    title: 'Build-A-Bear Workshop',
    description: 'Let little hands create big cuddles. In this Build-A-Bear workshop for kids, children choose a soft toy, fill and fluff it, customise it with patches, decorate the teddy tee, and take home a handmade keepsake. A safe, fun, and fully customisable teddy bear making activity ideal for birthday parties, kids workshops, and events (up to 10 years).',
    image: '/Kids-art/buildabear.webp',
    categories: [Category.KIDS, Category.RETURN_GIFTS]
  },
  {
    id: 'diy-sipper',
    title: 'Sipper Sticker Station',
    description: 'Looking for a unique, engaging, and mess-free activity for all ages? Our Sipper Sticker Station is an interactive DIY experience where guests choose their own sipper or tumbler and personalise it using vibrant themed stickers. Guests pick a sipper, browse sticker options, peel and paste, and walk away with a one-of-a-kind personalised keepsake. No paint, no glue, no mess - just creativity and fun. Suitable for kids, teens, and adults, this station encourages self-expression, keeps guests engaged, and works beautifully at birthday parties, school events, exhibitions, weddings, corporate events, and family gatherings.',
    image: '/Kids-art/sipper.webp',
    categories: [Category.KIDS, Category.RETURN_GIFTS, Category.CORPORATE_ADULT]
  },
  {
    id: 'bag-painting',
    title: 'Fanny Pouch Patches Workshop',
    description: 'Looking for a fun, hands-on activity that everyone can enjoy? Fanny Pouch Patches is an exciting, budget-friendly station where guests design their own trendy fanny pouch. Participants pick from vibrant pouch colours and customise with easy heat-and-press patches, from quirky icons and cute characters to funky symbols and stylish motifs. In minutes, guests of all ages create a personalised accessory they will actually use. This engaging, creative, and mess-free activity is perfect for parties, workshops, school events, and corporate gatherings. Creative. Interactive. Personal. A fun experience and stylish takeaway in one.',
    image: '/Kids-art/fannypouch.webp',
    categories: [Category.KIDS, Category.RETURN_GIFTS, Category.CORPORATE_ADULT]
  },
  {
    id: 'jacket-press',
    title: 'Jacket Printing Workshop',
    description: 'Turn creativity into wearable fashion. In this hands-on station, guests choose a denim jacket or hoodie, select colourful press-on patches, and use fabric paints, stencils, or prints to design a one-of-a-kind piece. It is an engaging, mess-controlled activity for all ages and a premium take-home keepsake, perfect for birthday parties, school and college events, exhibitions, and corporate gatherings.',
    image: '/Kids-art/jacketprint.webp',
    categories: [Category.KIDS, Category.CORPORATE_ADULT]
  },
  {
    id: 'ocean-art',
    title: 'Ocean Art Workshop',
    description: 'Create your own calming coastal masterpiece. Turn an MDF base into a realistic seaside scene using acrylic colours, clay, shells, moss, and natural textures. Add an optional resin finish for a stunning glassy wave effect.This hands-on mixed-media activity combines painting, sculpting, and design in one immersive experience. Perfect for kids workshops, birthdays, family sessions, school events, hobby classes, and adult resin workshops.Ocean Art builds creativity, focus, sensory development, and design skills while creating a beautiful display-ready artwork inspired by the sea.',
    image: '/Kids-art/oceanart.webp',
    categories: [Category.KIDS, Category.CORPORATE_ADULT]
  },
  {
    id: 'keychain',
    title: 'Keychain Workshop',
    description: 'Add a touch of creativity to your event with our Keychain Making station. We provide wooden initial cutouts, charms, hangings, pearls, tassels, and embellishments so guests can design a custom keychain. This simple, hands-on, and mess-free activity is suitable for all ages and creates a personalised, practical keepsake that guests can use every day. Ideal for parties, school events, workshops, exhibitions, and corporate gatherings.',
    image: '/Kids-art/keychain.webp',
    categories: [Category.KIDS, Category.RETURN_GIFTS]
  },
  {
    id: 'decoden',
    title: 'Decoden Art Workshop',
    description: 'Decoden Art (Fake Whipped Cream Art) is a joyful hands-on activity where guests pipe colourful acrylic cream-like paste onto items like hairbrushes, jewellery boxes, phone covers, and more. After creating swirls and textured bases, they decorate with cute charms, glitters, pearls, and embellishments to make a dazzling personalised keepsake. Perfect for kids, teens, and adults at birthday parties, school events, exhibitions, festive gatherings, and corporate workshops.',
    image: '/Kids-art/decoden.webp',
    categories: [Category.KIDS, Category.CORPORATE_ADULT]
  },
  {
    id: 'clay-nameplate',
    title: 'Clay Nameplate Workshop',
    description: 'Turn a simple board into a personalised piece of art. In this Clay Nameplate workshop, participants paint an MDF base, mold colourful clay into raised 3D elements (flowers, bees, fruits, leaves, and more), and finish with a wooden name cutout. Suitable for kids, teens, and adults (difficulty adjusted by age), this hands-on activity builds creativity, focus, and fine motor skills while creating a ready-to-hang keepsake for home or room decor.',
    image: '/Kids-art/clay.webp',
    categories: [Category.KIDS, Category.ALL]
  },
];

export const LIVE_STALLS: LiveStall[] = [
  { id: '1', title: 'Cap Printing', category: 'Craft' },
  { id: '2', title: 'Tee Printing', category: 'Craft' },
  { id: '3', title: 'Jacket Printing', category: 'Craft' },
  { id: '4', title: 'Face Painting', category: 'Entertainment' },
  { id: '5', title: 'Tattoo Art', category: 'Entertainment' },
  { id: '6', title: 'Stone Art', category: 'Craft' },
  { id: '7', title: 'Live Magnet', category: 'Craft' },
  { id: '8', title: 'Bouncy Castle / Slide', category: 'Entertainment' },
  { id: '9', title: 'Magic Show', category: 'Entertainment' },
  { id: '10', title: 'Science Show', category: 'Entertainment' },
  { id: '11', title: 'Puppet Show', category: 'Entertainment' },
  { id: '12', title: 'Story Telling', category: 'Entertainment' },
  { id: '13', title: 'Book Stall', category: 'Food/Gift' },
  { id: '14', title: 'Return Gift Stall', category: 'Food/Gift' },
  { id: '15', title: 'Crocs Station', category: 'Craft' },
  { id: '16', title: 'Beads Station', category: 'Craft' },
];

export const CONTACT_INFO = {
  phone: '+91 9999386566',
  email: 'Artistrybysonam@gmail.com',
  address: 'Bhama Shah Marg, Model Town, New Delhi- 110009',
};
